<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'adminSettings#get', 'url' => '/api/v1/admin/settings', 'verb' => 'GET'],
		['name' => 'adminSettings#update', 'url' => '/api/v1/admin/settings', 'verb' => 'PUT'],
		['name' => 'adminSettings#groups', 'url' => '/api/v1/admin/groups', 'verb' => 'GET'],
		['name' => 'adminSettings#logs', 'url' => '/api/v1/admin/logs', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatus', 'url' => '/api/v1/admin/auto_status', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSyncSlash', 'url' => '/api/v1/admin/auto-sync/status/', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSyncUnderscoreSlash', 'url' => '/api/v1/admin/auto_sync/status/', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSyncNoPuncSlash', 'url' => '/api/v1/admin/autosync/status/', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusLegacy', 'url' => '/api/v1/admin/auto-status', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusLegacySlash', 'url' => '/api/v1/admin/auto-status/', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSync', 'url' => '/api/v1/admin/auto-sync/status', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSyncUnderscore', 'url' => '/api/v1/admin/auto_sync/status', 'verb' => 'GET'],
		['name' => 'adminSettings#autoSyncStatusSyncNoPunc', 'url' => '/api/v1/admin/autosync/status', 'verb' => 'GET'],
		['name' => 'adminSettings#processAutoSync', 'url' => '/api/v1/admin/auto-sync/trigger', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSlash', 'url' => '/api/v1/admin/auto-sync/trigger/', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSync', 'url' => '/api/v1/admin/auto-sync/process-due', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSyncUnderscore', 'url' => '/api/v1/admin/auto_sync/process-due', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSyncNoPunc', 'url' => '/api/v1/admin/autosync/process-due', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSyncSlash', 'url' => '/api/v1/admin/auto-sync/process-due/', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSyncUnderscoreSlash', 'url' => '/api/v1/admin/auto_sync/process-due/', 'verb' => 'POST'],
		['name' => 'adminSettings#processAutoSyncSyncNoPuncSlash', 'url' => '/api/v1/admin/autosync/process-due/', 'verb' => 'POST'],
		['name' => 'diagnostics#adminReport', 'url' => '/api/v1/admin/diagnostics/report', 'verb' => 'GET'],
		['name' => 'userSettings#get', 'url' => '/api/v1/user/settings', 'verb' => 'GET'],
		['name' => 'userSettings#update', 'url' => '/api/v1/user/settings', 'verb' => 'PUT'],
		['name' => 'diagnostics#personalReport', 'url' => '/api/v1/diagnostics/report', 'verb' => 'GET'],
		['name' => 'folder#index', 'url' => '/api/v1/folders', 'verb' => 'GET'],
		['name' => 'preview#plan', 'url' => '/api/v1/preview', 'verb' => 'POST'],
		['name' => 'sync#dryRun', 'url' => '/api/v1/sync/dry-run', 'verb' => 'POST'],
		['name' => 'sync#write', 'url' => '/api/v1/sync/write', 'verb' => 'POST'],
		['name' => 'sync#runs', 'url' => '/api/v1/sync/runs', 'verb' => 'GET'],
		['name' => 'sync#status', 'url' => '/api/v1/sync/status', 'verb' => 'GET'],
		['name' => 'sync#queueUpdate', 'url' => '/api/v1/sync/queue-update', 'verb' => 'POST'],
		['name' => 'accountReset#dryRun', 'url' => '/api/v1/account/reset/dry-run', 'verb' => 'POST'],
		['name' => 'accountReset#reset', 'url' => '/api/v1/account/reset', 'verb' => 'POST'],
		['name' => 'managedAlbum#index', 'url' => '/api/v1/albums/managed', 'verb' => 'GET'],
		['name' => 'managedAlbum#prepareDownload', 'url' => '/api/v1/albums/managed/download/prepare', 'verb' => 'POST'],
		['name' => 'managedAlbum#download', 'url' => '/api/v1/albums/managed/download', 'verb' => 'GET'],
		['name' => 'albumExport#albums', 'url' => '/api/v1/albums/export/albums', 'verb' => 'GET'],
		['name' => 'albumExport#jobs', 'url' => '/api/v1/albums/export/jobs', 'verb' => 'GET'],
		['name' => 'albumExport#create', 'url' => '/api/v1/albums/export', 'verb' => 'POST'],
		['name' => 'albumExport#download', 'url' => '/api/v1/albums/export/download', 'verb' => 'GET'],
		['name' => 'managedAlbum#dryRunDelete', 'url' => '/api/v1/albums/delete/dry-run', 'verb' => 'POST'],
		['name' => 'managedAlbum#delete', 'url' => '/api/v1/albums/delete', 'verb' => 'POST'],
	],
];
